name: Run Tests

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    services:
      mysql:
        image: mysql:8.0.25
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: laravel
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.2, 8.3]
        dependency-version: [prefer-stable]

    name: P${{ matrix.php }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Install dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Install NPM dependencies
        run: npm install

      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: npm-

      - name: Compile assets
        run: npm run build

      - name: Copy .env && Generate Application Key
        run: |
          cp .env.ci .env
          php artisan key:generate
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: laravel
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USER: root
          DB_PASSWORD: password

      - name: Run sample Migrations
        run: |
          php artisan migrate --force --seed --no-interaction
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: laravel
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USER: root
          DB_PASSWORD: password

      - name: Execute & Run tests
        run: vendor/bin/phpunit
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: laravel
          DB_PORT: ${{ job.services.mysql.ports[3306] }}
          DB_USER: root
          DB_PASSWORD: password
